# Generated by Django 3.2.4 on 2021-07-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
