# Generated by Django 3.2.4 on 2021-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='course_id',
            field=models.ManyToManyField(blank=True, null=True, to='grades.Course'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='student_id',
            field=models.ManyToManyField(blank=True, null=True, to='grades.Student'),
        ),
    ]
