# Generated by Django 3.2.4 on 2021-07-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_auto_20210719_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Assignment Name')),
                ('assignment_date', models.DateField(verbose_name='Assignment Date')),
                ('assignment_due_date', models.DateField(verbose_name='Assignment Due Date')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
